# Generated by Django 5.1.4 on 2024-12-30 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_alter_note_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="completed",
        ),
    ]
